- name: add crontab for root
  copy:
    src: /var/spool/cron/crontabs/root
    #in dest what will be it's new name
    dest: /var/spool/cron/crontabs/
    owner: root
    group: crontab
    mode: 0600
  notify: 
      - restart_crontab
