---
   - name: install apache2 package (Ubuntu)
     hosts: all
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
